CREATE TABLE PRODUTOS_TESTEARECO (
	CODIGO_PRODUTO INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	PRECO_PRODUTO NUMERIC(8,2) NOT NULL,
	ESTOQUE_PRODUTO INT NOT NULL,
	CATEGORIA_PRODUTO CHAR(1) NOT NULL,
	SITUACAO_PRODUTO CHAR(1) NOT NULL
);